config/routes.rb
Rails.application.routes.draw do
  root "application#login"
  get "/login" => "logins#new"
  post "/login" => "logins#create"
  get "/logout" => "logins#destroy"
  resources :users, only: [:index, :edit, :update]
  resources :attendances, only: [:create, :update]
  namespace :admin do
    resources :users do
      put "lock"
      put "unlock"
    end
    resources :attendances, only: [:update, :destroy]
    resources :statistics, only: [:index] 
    resources :latelists, only: [:index] 
  end

  resources :change_passwords, only: [:edit, :update]
  get "*path" => redirect("/")

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    if logged_in?
      redirect_to users_path
    end
  end

  def create
    user = User.find_by(user_name: params[:login][:user_name]) ||
      User.find_by(email: params[:login][:user_name])
    if user && user.authenticate(params[:login][:password])
      if user.lock?
        flash.now[:danger] = t("controller.logins.lock")
        render :new
      else
        log_in user
        params[:login][:remember_me] == "1" ? remember(user) : forget(user)
        flash[:success] = t("controller.logins.success")
        redirect_to users_path
      end
    else
      flash.now[:danger] = t("controller.logins.invalid")
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_url
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def forget user
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user? user
    current_user.id == user.id
  end

end

app/views/logins/new.html.erb
<% provide(:title, t(".title")) %>
<body class="hold-transition login-page">
  <div class="alert-absolute">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> alert-dismissible">
        <button type="button" class="close" data-dismiss="alert"
          aria-hidden="true">×</button>
        <%= message %>
      </div>
    <% end %>
  </div>
  <div class="login-box">
    <div class="login-logo">
      <%= link_to(t(".app_name").html_safe, "/") %>
    </div>
    <div class="login-box-body">
      <p class="login-box-msg"><%= t(".title_login") %></p>
      <%= form_for(:login, url: login_path) do |f| %>
        <div class="form-group has-feedback">
          <%= f.text_field :user_name, class: "form-control",
            placeholder: "Username/Email" %>
          <span class="glyphicon glyphicon-envelope
            form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <%= f.password_field :password, class: "form-control",
            placeholder: "Password" %>
          <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <div class="row">
          <div class="col-xs-8">
            <div class="checkbox icheck">
              <label>
                <%= f.check_box :remember_me %> <%= t(".remember_me") %>
              </label>
            </div>
          </div>
          <div class="col-xs-4">
            <%= f.submit t(".title"), class: "btn btn-primary btn-block btn-flat" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <script>
    $(function () {
      $("input").iCheck({
        checkboxClass: "icheckbox_square-blue",
        radioClass: "iradio_square-blue",
        increaseArea: "20%"
      });
    });
  </script>
</body>