config/routes.rb
Rails.application.routes.draw do
  root "application#login"
  get "/login" => "logins#new"
  post "/login" => "logins#create"
  get "/logout" => "logins#destroy"
  resources :users, only: [:index, :edit, :update]
  resources :attendances, only: [:create, :update]
  namespace :admin do
    resources :users do
      put "lock"
      put "unlock"
    end
    resources :attendances, only: [:update, :destroy]
    resources :statistics, only: [:index] 
    resources :latelists, only: [:index] 
  end

  resources :change_passwords, only: [:edit, :update]
  get "*path" => redirect("/")

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token

  before_save :downcase_email

  validates :user_name, presence: true, length: {maximum: Settings.max_name},
    uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true, length: {maximum: Settings.max_email},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :full_name, presence:true, length: {maximum: Settings.max_name}
  validates :password, presence: true, length: {minimum: Settings.min_password}

  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def nearest_attendance
    attendance = attendances.first
    if attendance.nil?
      ""
    else
      attendance.date
    end
  end

  def today
    time_now = Time.zone.now
    attendance = Attendance.find_by(user_id: id, date: time_now)
    if attendance.nil?
      "Not attendance"
    elsif attendance.time_out.present?
      "Done"
    else
      "Attendanced"
    end
  end

  private
    def downcase_email
      self.email = email.downcase
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user
  before_action :require_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    time_now = Time.zone.now
    @this_month = time_now.strftime("%Y-%m")
    @attendances = {}
    @data = {}
    @user.attendances.each{|x|
      time_in = x.time_in.strftime("%H:%M")
      time_out = x.time_out.nil? ? "?" : x.time_out.strftime("%H:%M")
      @attendances[x.date.to_s] = {number: "#{time_in}<br>#{time_out}".html_safe}
      @data[x.date.to_s] = {id: x.id, time_in: time_in, time_out: time_out}
    }
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_user(@user).deliver
      flash[:success] = t("controller.users.success")
      redirect_to admin_users_url
    else
      flash.now[:danger] = t("controller.users.fail")
      render :new
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user.destroy
      flash[:success] = t("controller.users.success")
      redirect_to admin_users_url
    else
      flash.now[:danger] = t("controller.users.fail")
      redirect_to admin_users_url
    end
  end

  def lock
    @user = User.find_by(id: params[:user_id])
    @user.update_attribute(:lock, true)
    redirect_to admin_users_path
  end

  def unlock
    @user = User.find_by(id: params[:user_id])
    @user.update_attribute(:lock, false)
    redirect_to admin_users_path
  end

    


  private
  def user_params
    params.require(:user).permit(:full_name, :user_name, :email)
      .merge(password: Settings.default_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :require_change_password
  before_action :correct_user, only: [:edit, :update]

  def index
    time_now = Time.zone.now
    @this_month = time_now.strftime("%Y-%m")
    @attendances = {}
    current_user.attendances.each{|x|
      time_in = x.time_in.strftime("%H:%M")
      time_out = x.time_out.nil? ? "?" : x.time_out.strftime("%H:%M")
      @attendances[x.date.to_s] = {number: "#{time_in}<br>#{time_out}".html_safe}
    }
    @attendance = Attendance.find_by(user_id: current_user.id, date: time_now)
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = t("controller.users.success")
      redirect_to user_path
    else
      flash.now[:danger] = t("controller.users.fail")
      render :edit
    end
  end

  
  private
  def user_params
    params.require(:user).permit(:full_name, :email, :password,
      :password_confirmation)
  end
end

app/views/admin/users/index.html.erb
<% provide(:title, t(".title")) %>
<section class="content-header">
</section>
<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"><%= t(".title") %></h3>
        </div>
        <div class="box-body">
          <table class="table table-bordered table-striped table-responsive">
            <thead>
              <tr>
                <th><%= t(".id") %></th>
                <th><%= t(".full_name") %></th>
                <th><%= t(".nearest_attendance") %></th>
                <th><%= t(".today") %></th>
                <th>#</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.id %></td>
                  <td><%= link_to(user.full_name, admin_user_path(user.id),
                    data: {turbolinks: false}) %></td>
                  <td><%= user.nearest_attendance %></td>
                  <td><%= user.today %></td>
                  <td>
                    <% if !user.admin? %>
                      <% if user.lock? %>
                        <%= link_to(t(".unlock"), admin_user_unlock_path(user.id),
                          method: :put,
                          data: {confirm: t(".confirm")}) %>
                      <% else %>
                        <%= link_to(t(".lock"), admin_user_lock_path(user.id),
                          method: :put,
                          data: {confirm: t(".confirm")}) %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
           </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">    
      <a href="<%= admin_statistics_path %>"
        data-turbolinks="false" class="btn btn-primary btn-block" target="_blank">
        <%= t(".total") %>
      </a>
    </div>
  
 
    <div class="col-md-2">    
      <a href="<%= admin_latelists_path %>"
        data-turbolinks="false" class="btn btn-primary btn-block" target="_blank" >
        <%= t(".late") %>
      </a>
    </div>
  </div>
</section>

app/views/admin/users/new.html.erb
<% provide(:title, t(".title")) %>
<section class="content-header">
</section>
<section class="content">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"><%= t(".title") %></h3>
        </div>
        <%= form_for(:user, url: admin_users_path) do |f| %>
          <%= render "shared/error_messages" %>
          <div class="box-body">
            <div class="form-group">
              <%= f.label :full_name %>
              <%= f.text_field :full_name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :user_name %>
              <%= f.text_field :user_name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class: "form-control" %>
            </div>
          </div>
          <div class="box-footer">
            <%= f.submit t(".title"), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/admin/users/show.html.erb
<% provide(:title, t(".title")) %>
<section class="content-header">
</section>
<section class="content">
  <div class="row">
    <div class="col-md-5">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h4 class="box-title"><%= t(".user_profile") %></h4>
        </div>
        <div class="box-body">
          <div>
            <label><%= t(".full_name") %></label>
            <%= @user.full_name %>
          </div>
          <div>
            <label><%= t(".email") %></label>
            <%= @user.email %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-7">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h4 class="box-title"><%= t(".calendar") %></h4>
        </div>
        <div class="box-body">
          <div class="responsive-calendar">
            <div class="controls">
              <a class="pull-left" data-go="prev">
                <div class="btn btn-primary">Prev</div>
              </a>
              <h4><span data-head-year></span> <span data-head-month></span></h4>
              <a class="pull-right" data-go="next">
                <div class="btn btn-primary">Next</div>
              </a>
            </div>
            <hr/>
            <div class="day-headers">
              <div class="day header"><%= t(".mon") %></div>
              <div class="day header"><%= t(".tue") %></div>
              <div class="day header"><%= t(".wed") %></div>
              <div class="day header"><%= t(".thu") %></div>
              <div class="day header"><%= t(".fri") %></div>
              <div class="day header"><%= t(".sat") %></div>
              <div class="day header"><%= t(".sun") %></div>
            </div>
            <div class="days" data-group="days">
            </div>
          </div>
          <script type="text/javascript">
            $(document).ready(function () {
              var thisMonth = "<%= @this_month %>";
              showAttendanceOnCalendar(thisMonth, <%= raw @attendances.to_json %>);
              showModal(<%= raw @data.to_json %>);
            });
          </script>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="modal fade" id="attendance_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
          aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title"><%= t(".edit_attendance") %></h4>
      </div>
    <%= form_for(:attendance, url: "#", method: :put,
      :html=> {:id => "form-attendance"}) do |f| %>
      <div class="modal-body">
        <%= render "shared/error_messages" %>
        <%= f.hidden_field :year, value: @year %>
        <%= f.hidden_field :month, value: @month %>
        <%= f.label :date %>
        <%= f.date_field :date, class: "form-control date-attendance" %>
        <%= f.label :time_in %>
        <%= f.time_field :time_in, class: "form-control time-in-attendance" %>
        <%= f.label :time_out %>
        <%= f.time_field :time_out, class: "form-control time-out-attendance" %>
      </div>
      <div class="modal-footer">
        <%= f.submit t(".save"), class: "btn btn-primary" %>
        <a type="button" class="btn btn-primary pull-right delete-attendance"
          data-confirm="<%= t(".confirm") %>"
          data-method="delete"><%= t(".delete") %></a>
      </div>
    <% end %>
    </div>
  </div>
</div>