config/routes.rb
Rails.application.routes.draw do
  root "application#login"
  get "/login" => "logins#new"
  post "/login" => "logins#create"
  get "/logout" => "logins#destroy"
  resources :users, only: [:index, :edit, :update]
  resources :attendances, only: [:create, :update]
  namespace :admin do
    resources :users do
      put "lock"
      put "unlock"
    end
    resources :attendances, only: [:update, :destroy]
    resources :statistics, only: [:index] 
    resources :latelists, only: [:index] 
  end

  resources :change_passwords, only: [:edit, :update]
  get "*path" => redirect("/")

end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <%= t(".version") %>
  </div>
  <%= t(".copyright") %>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <a href="/" data-turbolinks="false" class="logo">
    <span class="logo-lg"><b><%= t(".home") %></b></span>
  </a>
  <nav class="navbar navbar-static-top">
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src=<%= image_url("user2-160x160.jpg") %>
              class="user-image" alt="User Image">
            <span class="hidden-xs"><%= current_user.full_name %></span>
          </a>
          <ul class="dropdown-menu">
            <% if current_user.admin? %>
              <li>
                <%= link_to(t(".create_user"), new_admin_user_path,
                      data: {turbolinks: false},
                      class: "btn") %>
              </li>
              <li>
                <a href="/admin/users" data-turbolinks="false"
                  class="btn">
                  <%= t(".manage_user") %>
                </a>
              </li>
            <% end %>
            <li>
              <a href=<%= edit_user_path(current_user) %>
                data-turbolinks="false" class="btn">
                <%= t(".profile") %>
              </a>
            </li>
            <li>
              <a href="/logout" class="btn">
                <%= t(".log_out") %>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<% if logged_in? %>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="alert-absolute">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          <i class="icon fa fa-ban"></i> <%= message %>
        </div>
      <% end %>
    </div>
    <div class="wrapper">
      <%= render "layouts/header" %>
      <div class="content-wrapper">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
<% else %>
  <%= yield %>
<% end %>
</html>